### ISSUE TITLE
Issue while running Feign sample

### ISSUE THREAD

**Issue by pradeepkusingh** [spring-cloud-samples/feign-eureka#1]
While running the HelloClient in Cloud foundry , I am getting unknownhostexception. Need your help to resolve this issue.

**Comment by dsyer** [comment]
Did you see the section in the user guide on "Using Eureka in Cloud Foundry" (http://projects.spring.io/spring-cloud/spring-cloud.html#_eureka_metadata_for_instances_and_clients)?
